site_name: TopHat Visualizations
theme: readthedocs
nav:
  - Home: index.md
  - Installation & usage: usage.md
  - Development: development.md
  - Testing: testing.md
  - Documentation: documetnation.md
