site_name: TopHat Visualizations
theme: readthedocs
repo_url: https://github.com/mark-gerarts/ou-afstuderen-artefact
nav:
  - Home: index.md
  - Installation & usage: usage.md
  - Development: development.md
  - Testing: testing.md
  - Documentation: documentation.md
