name:                ou-afstuderen-artefact
version:             0.1.0.0
github:              "githubuser/ou-afstuderen-artefact"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ou-afstuderen-artefact#readme>

dependencies:
- base-noprelude >= 4.7 && < 5
- warp
- wai
- wai-extra
- http-types
- async
- directory
- tophat
- containers
- unordered-containers
- servant-server
- servant
- http-media
- bytestring
- text
- aeson
- wai-app-static
- wai-cors
- polysemy >= 1.5.0 && < 2
- scientific
- hspec
- hspec-contrib
- QuickCheck

library:
  source-dirs: src

executables:
  ou-afstuderen-artefact-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ou-afstuderen-artefact

tests:
  ou-afstuderen-artefact-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ou-afstuderen-artefact
